### ISSUE TITLE
TypeError: $(...).find(...).gridstack is not a function

### ISSUE THREAD

**Issue by chevy07** [ApolloSSC/ng2-gridstack#7]
I am using your component and imported jquery(3.1.0), jquery-ui(1.12.1), lodash(4.14.2) and gridstack(0.2.6), but after I ran the code as below:
ts:
`import {GridStackComponent, GridStackItemDirective} from 'ng2-gridstack/ng2-gridstack';
@NgModule({
  declarations: [
    GridStackComponent,
    GridStackItemDirective
  ],
  imports: [
    CommonModule,
    FormsModule,
  ]
})`
html:
`<gridStack w="12" animate="true">
	<div gridStackItem
		[x]="0" [y]="0" [h]="3" [w]="3" [customid]="10">
		<h1>Hello</h1>
	</div>
</gridStack>`

The following error occurred, do you know how to solve it？

Error details:
TypeError: $(...).find(...).gridstack is not a function
    at GridStackComponent.webpackJsonpac__name_.1418.GridStackComponent.ngAfterViewInit

**Comment by gperouffe** [comment]
How did you import those libraries? Try adding this to your index.html if you did not already:

```html
<script src="path/to/jquery/3.1.1/jquery.min.js"></script>
<script src="path/to/jqueryui/1.11.2/jquery-ui.js"></script>
<script src="path/to/lodash.js/3.5.0/lodash.min.js"></script>
<script src="path/to/gridstack.js/0.2.6/gridstack.js"></script>

<link rel="stylesheet" href="path/to/gridstack.js/0.2.6/gridstack.css">
<link rel="stylesheet" href="path/to/ui/1.11.2/themes/smoothness/jquery-ui.css">
```

**Comment by chevy07** [comment]
I didn't use this kind of declaration. I use webpack to complie my website.
I declared them in package.json
    "jquery": "3.1.1",
    "jquery-ui": "git://github.com/jquery/jquery-ui.git#1.12.1",
    "lodash": "4.17.4",
    "gridstack": "0.2.6"

Have you used in this situation?

**Comment by gperouffe** [comment]
Please read [gridstack.js](https://github.com/troolee/gridstack.js) documentation. Package.json will not load your libraries in your web page, you need to include them somehow. Since they are JS libraries and not Angular ones, you should import them directly into your web page using the syntax of my previous comment.

**Comment by chevy07** [comment]
![untitled](https://cloud.githubusercontent.com/assets/28139224/25647000/cc4f6462-2ff0-11e7-9572-0517ae5c000c.jpg)
I got a result like the picture showed and there're no other errors after I imported all the related components.
import 'jquery';
import 'jquery-ui';
import 'lodash';
import 'gridstack';
import {GridStackComponent, GridStackItemDirective} from 'ng2-gridstack/ng2-gridstack';

Is there something wrong? Or I missed something?

**Comment by gperouffe** [comment]
Again, the gridstack dependencies are not TS libraries, but JS ones. You need to include them via script tags in your html.

**Comment by chevy07** [comment]
Now I followed your advise and imported the libraries in the html file. It seems that x, y attribute can be recognized but the element still cannot be drag and resize.
Do you have online demo or demo source code?

**Comment by gperouffe** [comment]
Sorry, I do not have any demo, nor have I time to make one right now.

**Comment by sebastienvermeille** [comment]
Well so basically I have the same problem. 

@chevy07 did you solve it ? if yes tell me how please

**Comment by RickvanOsta** [comment]
To solve this problem using _webpack_, do the following:

 - Install packages using _npm_

`npm install jquery-ui lodash gridstack --save-dev`

 - Create an alias in _webpack.config.js_
```
alias: {
            "lodash": "node_modules/lodash",
            "jquery-ui": "node_modules/jquery-ui",
            "gridstack": "node_modules/gridstack"
        }
```

 - Require the modules in your typescript file
```
require('lodash');
require('jquery-ui');
require('gridstack');
```

In order for _webpack_ to recognize which files to include in your bundle, you have to require them. The alias in your config file makes sure that _webpack_ knows where to actually find the files you're trying to include. Including the .js files in your _html_ file as **gperouffe** suggested does not work, especially when you're trying to combine both methods (including in _html_ and including through _webpack_). This is because they can't reference to eachother when they have dependencies.

Hope this helps!

**Comment by gperouffe** [comment]
Please try with the last release (1.0.0) and report back. See updated documentation to know how to import it. Let me know if there are other problems. I'm closing that for now.

**Comment by MikeGsus** [comment]
I've added the libraries as [gridstack.js](https://github.com/gridstack/gridstack.js) says, but I got the probleme yet
